# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1d2daf5dbc694e8047a3668633235d0f0f2db0e60c5cb9a5529ab4f7616c1521c3e57b3792dfb52f8bfa77d0bf6d37a349f374bb133fa3eb5eb45e412a92131

test:
  secret_key_base: 7da449c17e36cf600be93c251d6336896c9eff07353f64c4b759618bc6ae6e1779948384d0ffa4fffbaffdb37b1bd2b8b5bc79cc6859ab35c1d172a815ec9924

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
